export default {
  VIDEO_CHANGE: "videoChange",
  SET_VIDEO_LIST: "videoList",
  PLAY_VIDEO_LIST: "playVideoList",
  SEARCHED_LIST: "searchedList",
  ADD_CHANNEL: "addChannel",
  DELETE_CHANNEL: "deleteChannel",
  REMOVE_SEARCHED_LIST: "removeSearchedList",
  SET_DAY: "setDay",
  SYNC_CHANNEL: "syncChannel",
  TOGGLE_CHANNEL_ACTIVE: "toggleChannelActive",
  TOGGLE_HAMBURGER_ACTIVE: "toggleHamburgerActive",
  TOGGLE_YOUTUBE_ACTIVE: "toggleYoutubeActive",
  TOGGLE_WIDGET_ACTIVE: "toggleWidgetActive",
  MODAL_SEARCHED_YOUTUBE_LIST: "modalSearchedYoutubeList",
}
